### ISSUE TITLE
一些代码上的个人建议

### ISSUE THREAD

**Issue by Nephthelana** [ZeroRing233/Degrees-of-Lewdity-RobinMod#1]
1. 关于在柠檬水摊建议罗宾升级的选项，由于这个选项都是在名为Widgets Robin的passage中，名为lemonade_stand_options的widget里，所以可以直接在这个widget里新增选项，就不用在两个地方对整个lemonade_stand_options进行替换了；
![屏幕截图 2024-05-02 080302](https://github.com/ZeroRing233/Degrees-of-Lewdity-RobinMod/assets/153483365/7a53689d-1ff8-43d3-a04f-d3bbd821b672)

2. 参照模组编写助手的提示：
![屏幕截图 2024-05-02 080424](https://github.com/ZeroRing233/Degrees-of-Lewdity-RobinMod/assets/153483365/828266d9-4fc7-4656-ba9c-93d70689a3d4)

`新招牌上的太阳仿佛正散发着温暖的光芒。`这句提示在boot里可以使用 `<<print $robin.timer.hurt` 来定位，取代之前用的 `你看到罗宾站在ta的柠檬水摊后面。`（当然，txt里也要进行相应的改动）
![屏幕截图 2024-05-02 080206](https://github.com/ZeroRing233/Degrees-of-Lewdity-RobinMod/assets/153483365/c1c14091-731b-4785-92f0-f8f60f82a269)

3. 对于每周增加600英镑收入的机制，可以在游戏中检查每周结束时的，名为`time.js`文件里的函数`weekPassed()`里增加判定及对应的结果。原来的写法来看，似乎只有PC当周进入房间时才会增加收入（）
![屏幕截图 2024-05-02 080941](https://github.com/ZeroRing233/Degrees-of-Lewdity-RobinMod/assets/153483365/e4d0117a-39a5-433a-aa98-cf2d778622a8)

最后是我修改好的模组文件。我只有简单用模组管理器加载后看到管理器没有报错，没有试出来游戏内的报错。如果有报错什么的欢迎来贴吧找我（id：脸木挤白）交流！
[robinMod.mod.zip](https://github.com/ZeroRing233/Degrees-of-Lewdity-RobinMod/files/15182431/robinMod.mod.zip)

**Comment by ZeroRing233** [comment]
收到！实在是太贴心了~
